#pragma once

#define APPLEMIDI_NAMESPACE appleMidi
#define BEGIN_APPLEMIDI_NAMESPACE \
    namespace APPLEMIDI_NAMESPACE \
    {
#define END_APPLEMIDI_NAMESPACE }

#define USING_NAMESPACE_APPLEMIDI using namespace APPLEMIDI_NAMESPACE;

BEGIN_APPLEMIDI_NAMESPACE

END_APPLEMIDI_NAMESPACE